export default{
    name:"index",
    api:{
        getIndexData:{
            url:'/getIndexData',
            method:'get',
            corsUrl:"/3001"
        },
        getCateGoryData:{
            url:'/getCateGoryData',
            method:'get',
            corsUrl:"/3001"
        },
        cateNavDatas:{
            url:'/cateNavDatas',
            method:'get',
            corsUrl:"/3001"
        },
        cateLists:{
            url:'/cateLists',
            method:'get',
            corsUrl:"/3001"
        },
        getIndexCateListData:{
            url:'/getIndexCateListData',
            method:'get',
            corsUrl:"/3001"
        },
        getKeyWord:{
            url:'/xhr/search/init.json',
            method:'get',
            corsUrl:"/api"
        },
        getKeyWordList:{
            url:'xhr/search/searchAutoComplete.json',
            method:'get',
            corsUrl:"/api"
        }
    },
}